package protocol

import (
	"encoding/binary"
	"fmt"
)

type AxisStatus struct {
	IsMoving             bool
	ModePositioning      bool
	ModeAbsolute         bool
	IsFindingEdge        bool
	IsHoming             bool
	HomePhase1Complete   bool
	HomePhase2Complete   bool
	ModeCoordinated      bool
	NegativeDirection    bool
	ModeContour          bool
	IsSlewing            bool
	IsStopping           bool
	IsDecelerating       bool
	LatchArmed           bool
	HomePhase3InProgress bool
	IsMotorDisabled      bool
}

type AxisSwitches struct {
	HasLatch        bool
	LatchInputState bool
	LimitForward    bool
	LimitReverse    bool
	LimitHome       bool
	ModeStepper     bool
}

type AxisRecord struct {
	Status            AxisStatus
	Switches          AxisSwitches
	StopCode          uint8
	ReferencePosition int32
	Position          int32
	PositionError     int32
	Velocity          int32
	Torque            int16
}

// Returns the current position in motor counts
func (d *DMC41x3) GetPosition(axis rune) (float64, error) {
	cmd := fmt.Sprintf("TD%c", axis)
	return d.QueryFloat64(cmd)
}

// Returns the reference position generated by the
// motion profiler in motor counts
func (d *DMC41x3) GetReferencePosition(axis rune) (float64, error) {
	cmd := fmt.Sprintf("RP%c", axis)
	return d.QueryFloat64(cmd)
}

// Returns the current velocity in counts/s
func (d *DMC41x3) GetVelocity(axis rune) (float64, error) {
	cmd := fmt.Sprintf("TV%c", axis)
	return d.QueryFloat64(cmd)
}

// Reports the digital torque value being output.
// Range ±32767, where 32767 is max positive voltage
func (d *DMC41x3) GetTorque(axis rune) (float64, error) {
	cmd := fmt.Sprintf("TT%c", axis)
	return d.QueryFloat64(cmd)
}

// Returns the logic state of digital input as a bitmask
func (d *DMC41x3) GetInputs() (int, error) {
	return d.QueryInt("TI")
}

// Returns the status bits of limit switches, home input, and
// motion status as a bitmask
func (d *DMC41x3) GetSwitches(axis rune) (int, error) {
	cmd := fmt.Sprintf("TS%c", axis)
	return d.QueryInt(cmd)
}

// Returns the active state of forward limit switch
func (d *DMC41x3) IsForwardSwitchOn(axis rune) (bool, error) {
	cmd := fmt.Sprintf("MG _LF%c", axis)
	response, err := d.QueryFloat64(cmd)
	if err != nil {
		return false, err
	}
	return response == 0, nil
}

// Returns the active state of reverse limit switch
func (d *DMC41x3) IsReverseSwitchOn(axis rune) (bool, error) {
	cmd := fmt.Sprintf("MG _LR%c", axis)
	response, err := d.QueryFloat64(cmd)
	if err != nil {
		return false, err
	}
	return response == 0, nil
}

// Returns the active state of home switch
func (d *DMC41x3) IsHomeSwitchOn(axis rune) (bool, error) {
	cmd := fmt.Sprintf("MG _HM%c", axis)
	response, err := d.QueryFloat64(cmd)
	if err != nil {
		return false, err
	}
	return response == 0, nil
}

// Returns the moving status
func (d *DMC41x3) IsMoving(axis rune) (bool, error) {
	cmd := fmt.Sprintf("MG _BG%c", axis)
	response, err := d.QueryFloat64(cmd)
	if err != nil {
		return false, err
	}
	return response == 1, nil
}

// Returns the record data from all axes
func (d *DMC41x3) GetRecord() (map[rune]AxisRecord, error) {
	info, err := d.GetDataRecordInformation()
	if err != nil {
		return nil, err
	}
	totalSize := info.NumberBytesInGeneralBlock + (info.NumberAxes * info.NumberBytesInAxisBlock)

	d.mutex.Lock()
	defer d.mutex.Unlock()

	if err := d.write("QR"); err != nil {
		d.mutex.Unlock()
		return nil, err
	}
	data, err := d.Communication.Read(uint(totalSize))
	if err != nil {
		return nil, err
	}
	if len(data) < totalSize {
		return nil, fmt.Errorf("buffer invalid: expected %d, got %d", totalSize, len(data))
	}

	records := make(map[rune]AxisRecord)
	axesNames := []rune{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'}

	offset := info.NumberBytesInGeneralBlock
	for i := 0; i < info.NumberAxes; i++ {
		axisData := data[offset : offset+info.NumberBytesInAxisBlock]
		b1 := axisData[0]
		b2 := axisData[1]
		sw := axisData[2]

		records[axesNames[i]] = AxisRecord{
			Status: AxisStatus{
				IsMoving:             (b1 & 0x80) != 0,
				ModePositioning:      (b1 & 0x40) != 0,
				NegativeDirection:    (b1 & 0x20) != 0,
				ModeContour:          (b1 & 0x10) != 0,
				IsStopping:           (b1 & 0x08) != 0,
				IsSlewing:            (b1 & 0x04) != 0,
				IsDecelerating:       (b1 & 0x02) != 0,
				IsMotorDisabled:      (b1 & 0x01) != 0,
				HomePhase3InProgress: (b2 & 0x80) != 0,
				LatchArmed:           (b2 & 0x40) != 0,
				HomePhase2Complete:   (b2 & 0x20) != 0,
				HomePhase1Complete:   (b2 & 0x10) != 0,
				IsFindingEdge:        (b2 & 0x08) != 0,
				IsHoming:             (b2 & 0x04) != 0,
				ModeAbsolute:         (b2 & 0x02) != 0,
				ModeCoordinated:      (b2 & 0x01) != 0,
			},
			Switches: AxisSwitches{
				HasLatch:        (sw & 0x01) != 0,
				LatchInputState: (sw & 0x02) != 0,
				LimitForward:    (sw & 0x04) != 0,
				LimitReverse:    (sw & 0x08) != 0,
				LimitHome:       (sw & 0x10) != 0,
				ModeStepper:     (sw & 0x80) != 0,
			},
			StopCode:          uint8(axisData[3]),
			ReferencePosition: int32(binary.LittleEndian.Uint32(axisData[4:8])),
			Position:          int32(binary.LittleEndian.Uint32(axisData[8:12])),
			PositionError:     int32(binary.LittleEndian.Uint32(axisData[12:16])),
			Velocity:          int32(binary.LittleEndian.Uint32(axisData[20:24])),
			Torque:            int16(binary.LittleEndian.Uint16(axisData[24:26])),
		}
		offset += info.NumberBytesInAxisBlock
	}

	return records, nil
}
